---
- name: Playbook for Route table for  Private
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set up private subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-03397932ec4cfdbce
        region: us-east-1
        tags:
          Name: private
        subnets:
          - subnet-0b1f0db7b921f14b9
          - subnet-090f0cba555b8e0b8
          - subnet-03122eddcbc81e410
        routes:
          - dest: 10.0.0.0/16
      register: private_route_table