---
- name: Playbook for task
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: Download woedpress
      get_url:
        url: "https://wordpress.org/wordpress-5.2.3.zip
        dest: /tmp/
    - name: install unzip
      package:
        name: unzip
        state: present
    -  name: unzip
       unarchive:
         src: /tmp/wordpress-5.2.3.zip
         dest: /tmp
         remote_src: yes
       ignore_errors: true  
  