---
- name: Playbook for upgrading kernel
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks: 
    - name: register
      shell: uname -r
      register: message

    - name: Debug
      debug:
        msg: "{{message}}"

    - name: upgrade kernel
      package:
        name: kernel
        state: latest

    - name: Reboot
      shell: "shutdown -r now"

    - name: wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
        delay: 60
        timeout: 300

   - name: register
      shell: uname -r
      register: message

    - name: Debug
      debug:
        msg: "{{message}}"