---
- name: Playbook for provisioning 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - ec2:
        key_name: Anisble_key
        instance_type: "{{instance_type}}"
        image: ami-04cf43aca3e6f3de3
        wait: yes
        group: webserver
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}}"
        assign_public_ip: yes
        region: "{{region}}"